#pragma once

struct PokedexEntry
{
    /*0x00*/ u8 categoryName[12];
    /*0x0C*/ u16 height; //in decimeters
    /*0x0E*/ u16 weight; //in hectograms
    /*0x10*/ const u8* description;
    /*0x14*/ const u8* unusedDescription;
    /*0x18*/ u16 unused;
    /*0x1A*/ u16 pokemonScale;
    /*0x1C*/ u16 pokemonOffset;
    /*0x1E*/ u16 trainerScale;
    /*0x20*/ u16 trainerOffset;
	/*0x22*/ u16 unused2;
};  /*size = 0x24*/

struct AlternateDexEntries
{
	u16 species;
	const u8* description;
};

struct ListMenuItem
{
    const u8* name;
    s32 id;
};

struct PokedexScreenData
{
    u8 field_00;
    u8 field_01;
    u8 field_02;
    u8 field_03;
    u8 field_04;
    u32 field_08;
    u32 field_0C;
    u16 field_10;
    u16 field_12;
    u8 field_14;
    u8 field_15;
    u8 field_16;
    u8 field_17;
    u16 field_18[0x4];
    u8 field_20[0x4];
    u8 field_24[0x4];
    u8 field_28;
    u8 field_29;
    u8 field_2A;
    u8 field_2B;
    u8 field_2C;
    u8 field_2D;
    u8 field_2E;
    u8 field_2F;
    u32 field_30;
    u16 field_34;
    u16 field_36;
    u16 field_38;
    u16 field_3A;
    u16 field_3C;
    u16 field_3E;
    u8 field_40;
    u8 field_41;
    u8 field_42;
    struct ListMenuItem* listItem;
    u16 field_48;
    u8 field_4A[0x10];
    u16 field_5A;
    u16 * field_5C;
    u8 field_60;
    u8 field_61;
    u16 field_62;
    u8 field_64;
    u16 field_66;
    u16 field_68;
    u16 field_6A;
    u16 field_6C;
};

extern struct PokedexScreenData* gPokedexScreenDataPtr;

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

// Kulure Dex
#define NATIONAL_DEX_NONE 0
#define NATIONAL_DEX_BIDOOF 1
#define NATIONAL_DEX_BIBAREL 2
#define NATIONAL_DEX_ROOKIDEE 3
#define NATIONAL_DEX_CORVISQUIRE 4
#define NATIONAL_DEX_CORVIKNIGHT 5
#define NATIONAL_DEX_SUNKERN 6
#define NATIONAL_DEX_SUNFLORA 7
#define NATIONAL_DEX_YAMPER 8
#define NATIONAL_DEX_BOLTUND 9
#define NATIONAL_DEX_BUDEW 10
#define NATIONAL_DEX_ROSELIA 11
#define NATIONAL_DEX_ROSERADE 12
#define NATIONAL_DEX_GRUBBIN 13
#define NATIONAL_DEX_CHARJABUG 14
#define NATIONAL_DEX_VIKAVOLT 15
#define NATIONAL_DEX_ROCKRUFF 16
#define NATIONAL_DEX_LYCANROC 17
#define NATIONAL_DEX_NICKIT 18
#define NATIONAL_DEX_THIEVUL 19
#define NATIONAL_DEX_NIDORAN_M 20
#define NATIONAL_DEX_NIDORINO 21
#define NATIONAL_DEX_NIDOKING 22
#define NATIONAL_DEX_BLIPBUG 23
#define NATIONAL_DEX_DOTTLER 24
#define NATIONAL_DEX_ORBEETLE 25
#define NATIONAL_DEX_PIKIPEK 26
#define NATIONAL_DEX_TRUMBEAK 27
#define NATIONAL_DEX_TOUCANNON 28
#define NATIONAL_DEX_MORELULL 29
#define NATIONAL_DEX_SHIINOTIC 30
#define NATIONAL_DEX_HOOTHOOT 31
#define NATIONAL_DEX_NOCTOWL 32
#define NATIONAL_DEX_PICHU 33
#define NATIONAL_DEX_PIKACHU 34
#define NATIONAL_DEX_RAICHU 35
#define NATIONAL_DEX_BUNEARY 36
#define NATIONAL_DEX_LOPUNNY 37
#define NATIONAL_DEX_SHROOMISH 38
#define NATIONAL_DEX_BRELOOM 39
#define NATIONAL_DEX_BONSLY 40
#define NATIONAL_DEX_SUDOWOODO 41
#define NATIONAL_DEX_VENIPEDE 42
#define NATIONAL_DEX_WHIRLIPEDE 43
#define NATIONAL_DEX_SCOLIPEDE 44
#define NATIONAL_DEX_SLAKOTH 45
#define NATIONAL_DEX_VIGOROTH 46
#define NATIONAL_DEX_SLAKING 47
#define NATIONAL_DEX_ZUBAT 48
#define NATIONAL_DEX_GOLBAT 49
#define NATIONAL_DEX_CROBAT 50
#define NATIONAL_DEX_DRILBUR 51
#define NATIONAL_DEX_EXCADRILL 52
#define NATIONAL_DEX_ROGGENROLA 53
#define NATIONAL_DEX_BOLDORE 54
#define NATIONAL_DEX_GIGALITH 55
#define NATIONAL_DEX_LILLIPUP 56
#define NATIONAL_DEX_HERDIER 57
#define NATIONAL_DEX_STOUTLAND 58
#define NATIONAL_DEX_CHINCHOU 59
#define NATIONAL_DEX_LANTURN 60
#define NATIONAL_DEX_RATTATA 61
#define NATIONAL_DEX_RATICATE 62
#define NATIONAL_DEX_FARFETCHD 63
#define NATIONAL_DEX_SIRFETCHD 64
#define NATIONAL_DEX_FLETCHLING 65
#define NATIONAL_DEX_FLETCHINDER 66
#define NATIONAL_DEX_TALONFLAME 67
#define NATIONAL_DEX_FLABEBE 68
#define NATIONAL_DEX_FLOETTE 69
#define NATIONAL_DEX_FLORGES 70
#define NATIONAL_DEX_CUTIEFLY 71
#define NATIONAL_DEX_RIBOMBEE 72
#define NATIONAL_DEX_RALTS 73
#define NATIONAL_DEX_KIRLIA 74
#define NATIONAL_DEX_GARDEVOIR 75
#define NATIONAL_DEX_GALLADE 76
#define NATIONAL_DEX_FERROSEED 77
#define NATIONAL_DEX_FERROTHORN 78
#define NATIONAL_DEX_COMBEE 79
#define NATIONAL_DEX_VESPIQUEN 80
#define NATIONAL_DEX_SCRAGGY 81
#define NATIONAL_DEX_SCRAFTY 82
#define NATIONAL_DEX_CACNEA 83
#define NATIONAL_DEX_CACTURNE 84
#define NATIONAL_DEX_WINGULL 85
#define NATIONAL_DEX_PELIPPER 86
#define NATIONAL_DEX_HELIOPTILE 87
#define NATIONAL_DEX_HELIOLISK 88
#define NATIONAL_DEX_VULLABY 89
#define NATIONAL_DEX_MANDIBUZZ 90
#define NATIONAL_DEX_CASTFORM 91
#define NATIONAL_DEX_CASTFORM 91
#define NATIONAL_DEX_CASTFORM 91
#define NATIONAL_DEX_CASTFORM 91
#define NATIONAL_DEX_TRAPINCH 92
#define NATIONAL_DEX_VIBRAVA 93
#define NATIONAL_DEX_FLYGON 94
#define NATIONAL_DEX_SANDILE 95
#define NATIONAL_DEX_KROKOROK 96
#define NATIONAL_DEX_KROOKODILE 97
#define NATIONAL_DEX_HIPPOPOTAS 98
#define NATIONAL_DEX_HIPPOWDON 99
#define NATIONAL_DEX_CORPHISH 100
#define NATIONAL_DEX_CRAWDAUNT 101
#define NATIONAL_DEX_MAGIKARP 102
#define NATIONAL_DEX_GYARADOS 103
#define NATIONAL_DEX_INKAY 104
#define NATIONAL_DEX_MALAMAR 105
#define NATIONAL_DEX_NINCADA 106
#define NATIONAL_DEX_NINJASK 107
#define NATIONAL_DEX_SHEDINJA 108
#define NATIONAL_DEX_WYNAUT 109
#define NATIONAL_DEX_WOBBUFFET 110
#define NATIONAL_DEX_CARBINK 111
#define NATIONAL_DEX_KLINK 112
#define NATIONAL_DEX_KLANG 113
#define NATIONAL_DEX_KLINKLANG 114
#define NATIONAL_DEX_SABLEYE 115
#define NATIONAL_DEX_MAWILE 116
#define NATIONAL_DEX_SHUCKLE 117
#define NATIONAL_DEX_JANGMO_O 118
#define NATIONAL_DEX_HAKAMO_O 119
#define NATIONAL_DEX_KOMMO_O 120
#define NATIONAL_DEX_CUBCHOO 121
#define NATIONAL_DEX_BEARTIC 122
#define NATIONAL_DEX_SWINUB 123
#define NATIONAL_DEX_PILOSWINE 124
#define NATIONAL_DEX_MAMOSWINE 125
#define NATIONAL_DEX_SNORUNT 126
#define NATIONAL_DEX_GLALIE 127
#define NATIONAL_DEX_FROSLASS 128
#define NATIONAL_DEX_NOIBAT 129
#define NATIONAL_DEX_NOIVERN 130
#define NATIONAL_DEX_TYRUNT 131
#define NATIONAL_DEX_TYRANTRUM 132
#define NATIONAL_DEX_SNEASEL 133
#define NATIONAL_DEX_WEAVILE 134
#define NATIONAL_DEX_SNOM 135
#define NATIONAL_DEX_FROSMOTH 136
#define NATIONAL_DEX_DARUMAKA 137
#define NATIONAL_DEX_DARMANITAN 138
#define NATIONAL_DEX_HOUNDOUR 139
#define NATIONAL_DEX_HOUNDOOM 140
#define NATIONAL_DEX_LARVESTA 141
#define NATIONAL_DEX_VOLCARONA 142
#define NATIONAL_DEX_MINIOR 143
#define NATIONAL_DEX_ROLYCOLY 144
#define NATIONAL_DEX_CARKOL 145
#define NATIONAL_DEX_COALOSSAL 146
#define NATIONAL_DEX_SKARMORY 147
#define NATIONAL_DEX_SALANDIT 148
#define NATIONAL_DEX_SALAZZLE 149
#define NATIONAL_DEX_FRILLISH 150
#define NATIONAL_DEX_JELLICENT 151
#define NATIONAL_DEX_FOONGUS 152
#define NATIONAL_DEX_AMOONGUSS 153
#define NATIONAL_DEX_SHIELDON 154
#define NATIONAL_DEX_BASTIODON 155
#define NATIONAL_DEX_TIMBURR 156
#define NATIONAL_DEX_GURDURR 157
#define NATIONAL_DEX_CONKELDURR 158
#define NATIONAL_DEX_AMAURA 159
#define NATIONAL_DEX_AURORUS 160
#define NATIONAL_DEX_TURTONATOR 161
#define NATIONAL_DEX_MIME_JR 162
#define NATIONAL_DEX_MR_MIME 163
#define NATIONAL_DEX_MR_RIME 164
#define NATIONAL_DEX_SLUGMA 165
#define NATIONAL_DEX_MAGCARGO 166
#define NATIONAL_DEX_HATENNA 167
#define NATIONAL_DEX_HATTREM 168
#define NATIONAL_DEX_HATTERENE 169
#define NATIONAL_DEX_ORANGURU 170
#define NATIONAL_DEX_PASSIMIAN 171
#define NATIONAL_DEX_TORKOAL 172
#define NATIONAL_DEX_LILEEP 173
#define NATIONAL_DEX_CRADILY 174
#define NATIONAL_DEX_SHELLDER 175
#define NATIONAL_DEX_CLOYSTER 176
#define NATIONAL_DEX_SIZZLIPEDE 177
#define NATIONAL_DEX_CENTISKORCH 178
#define NATIONAL_DEX_COTTONEE 179
#define NATIONAL_DEX_WHIMSICOTT 180
#define NATIONAL_DEX_DITTO 181
#define NATIONAL_DEX_EEVEE 182
#define NATIONAL_DEX_VAPOREON 183
#define NATIONAL_DEX_JOLTEON 184
#define NATIONAL_DEX_FLAREON 185
#define NATIONAL_DEX_ESPEON 186
#define NATIONAL_DEX_UMBREON 187
#define NATIONAL_DEX_LEAFEON 188
#define NATIONAL_DEX_GLACEON 189
#define NATIONAL_DEX_SYLVEON 190
#define NATIONAL_DEX_MAREEP 191
#define NATIONAL_DEX_FLAAFFY 192
#define NATIONAL_DEX_AMPHAROS 193
#define NATIONAL_DEX_TOGEPI 194
#define NATIONAL_DEX_TOGETIC 195
#define NATIONAL_DEX_TOGEKISS 196
#define NATIONAL_DEX_MUDBRAY 197
#define NATIONAL_DEX_MUDSDALE 198
#define NATIONAL_DEX_HAPPINY 199
#define NATIONAL_DEX_CHANSEY 200
#define NATIONAL_DEX_BLISSEY 201
#define NATIONAL_DEX_MIENFOO 202
#define NATIONAL_DEX_MIENSHAO 203
#define NATIONAL_DEX_SKIDDO 204
#define NATIONAL_DEX_GOGOAT 205
#define NATIONAL_DEX_RIOLU 206
#define NATIONAL_DEX_LUCARIO 207
#define NATIONAL_DEX_DRATINI 208
#define NATIONAL_DEX_DRAGONAIR 209
#define NATIONAL_DEX_DRAGONITE 210
#define NATIONAL_DEX_PACHIRISU 211
#define NATIONAL_DEX_ROTOM 212
#define NATIONAL_DEX_TOXEL 213
#define NATIONAL_DEX_TOXTRICITY 214
#define NATIONAL_DEX_HORSEA 215
#define NATIONAL_DEX_SEADRA 216
#define NATIONAL_DEX_KINGDRA 217
#define NATIONAL_DEX_CROAGUNK 218
#define NATIONAL_DEX_TOXICROAK 219
#define NATIONAL_DEX_GOOMY 220
#define NATIONAL_DEX_SLIGGOO 221
#define NATIONAL_DEX_GOODRA 222
#define NATIONAL_DEX_SHELLOS 223
#define NATIONAL_DEX_GASTRODON 224
#define NATIONAL_DEX_MIMIKYU 225
#define NATIONAL_DEX_DUSKULL 226
#define NATIONAL_DEX_DUSCLOPS 227
#define NATIONAL_DEX_DUSKNOIR 228
#define NATIONAL_DEX_EMOLGA 229
#define NATIONAL_DEX_CARVANHA 230
#define NATIONAL_DEX_SHARPEDO 231
#define NATIONAL_DEX_HERACROSS 232
#define NATIONAL_DEX_YAMASK 233
#define NATIONAL_DEX_COFAGRIGUS 234
#define NATIONAL_DEX_RUNERIGUS 235
#define NATIONAL_DEX_DHELMISE 236
#define NATIONAL_DEX_PINCURCHIN 237
#define NATIONAL_DEX_MORPEKO 238
#define NATIONAL_DEX_STUNFISK 239
#define NATIONAL_DEX_MISDREAVUS 240
#define NATIONAL_DEX_MISMAGIUS 241
#define NATIONAL_DEX_GRIMER 242
#define NATIONAL_DEX_MUK 243
#define NATIONAL_DEX_GIBLE 244
#define NATIONAL_DEX_GABITE 245
#define NATIONAL_DEX_GARCHOMP 246
#define NATIONAL_DEX_BINACLE 247
#define NATIONAL_DEX_BARBARACLE 248
#define NATIONAL_DEX_MAREANIE 249
#define NATIONAL_DEX_TOXAPEX 250
#define NATIONAL_DEX_KOFFING 251
#define NATIONAL_DEX_WEEZING 252
#define NATIONAL_DEX_ZORUA 253
#define NATIONAL_DEX_ZOROARK 254
#define NATIONAL_DEX_LAPRAS 255
#define NATIONAL_DEX_CRABRAWLER 256
#define NATIONAL_DEX_CRABOMINABLE 257
#define NATIONAL_DEX_PHANTUMP 258
#define NATIONAL_DEX_TREVENANT 259
#define NATIONAL_DEX_SANDYGAST 260
#define NATIONAL_DEX_PALOSSAND 261
#define NATIONAL_DEX_SLOWPOKE 262
#define NATIONAL_DEX_SLOWBRO 263
#define NATIONAL_DEX_SLOWKING 264
#define NATIONAL_DEX_CORSOLA 265
#define NATIONAL_DEX_CURSOLA 266
#define NATIONAL_DEX_FALINKS 267
#define NATIONAL_DEX_PAWNIARD 268
#define NATIONAL_DEX_BISHARP 269
#define NATIONAL_DEX_ELGYEM 270
#define NATIONAL_DEX_BEHEEYEM 271
#define NATIONAL_DEX_MANKEY 272
#define NATIONAL_DEX_PRIMEAPE 273
#define NATIONAL_DEX_BERGMITE 274
#define NATIONAL_DEX_AVALUGG 275
#define NATIONAL_DEX_STONJOURNER 276
#define NATIONAL_DEX_DELIBIRD 277
#define NATIONAL_DEX_COMFEY 278
#define NATIONAL_DEX_CUFANT 279
#define NATIONAL_DEX_COPPERAJAH 280
#define NATIONAL_DEX_JOLTIK 281
#define NATIONAL_DEX_GALVANTULA 282
#define NATIONAL_DEX_CARNIVINE 283
#define NATIONAL_DEX_LITLEO 284
#define NATIONAL_DEX_PYROAR 285
#define NATIONAL_DEX_KANGASKHAN 286
#define NATIONAL_DEX_DURALUDON 287

// Legendaries
#define NATIONAL_DEX_ARTICUNO 288
#define NATIONAL_DEX_ZAPDOS 289
#define NATIONAL_DEX_MOLTRES 290
#define NATIONAL_DEX_JIRACHI 291
#define NATIONAL_DEX_SHAYMIN 292
#define NATIONAL_DEX_KYOGRE 293
#define NATIONAL_DEX_GROUDON 294
#define NATIONAL_DEX_VOLCANION 295
#define NATIONAL_DEX_ZERAORA 296
#define NATIONAL_DEX_GLASTRIER 297
#define NATIONAL_DEX_MELTAN 298
#define NATIONAL_DEX_MELMETAL 299
#define NATIONAL_DEX_VICTINI 300

// Starters and UBs
#define NATIONAL_DEX_BULBASAUR 301
#define NATIONAL_DEX_IVYSAUR 302
#define NATIONAL_DEX_VENUSAUR 303
#define NATIONAL_DEX_CHARMANDER 304
#define NATIONAL_DEX_CHARMELEON 305
#define NATIONAL_DEX_CHARIZARD 306
#define NATIONAL_DEX_SQUIRTLE 307
#define NATIONAL_DEX_WARTORTLE 308
#define NATIONAL_DEX_BLASTOISE 309
#define NATIONAL_DEX_CHIKORITA 310
#define NATIONAL_DEX_BAYLEEF 311
#define NATIONAL_DEX_MEGANIUM 312
#define NATIONAL_DEX_CYNDAQUIL 313
#define NATIONAL_DEX_QUILAVA 314
#define NATIONAL_DEX_TYPHLOSION 315
#define NATIONAL_DEX_TOTODILE 316
#define NATIONAL_DEX_CROCONAW 317
#define NATIONAL_DEX_FERALIGATR 318
#define NATIONAL_DEX_TREECKO 319
#define NATIONAL_DEX_GROVYLE 320
#define NATIONAL_DEX_SCEPTILE 321
#define NATIONAL_DEX_TORCHIC 322
#define NATIONAL_DEX_COMBUSKEN 323
#define NATIONAL_DEX_BLAZIKEN 324
#define NATIONAL_DEX_MUDKIP 325
#define NATIONAL_DEX_MARSHTOMP 326
#define NATIONAL_DEX_SWAMPERT 327
#define NATIONAL_DEX_TURTWIG 328
#define NATIONAL_DEX_GROTLE 329
#define NATIONAL_DEX_TORTERRA 330
#define NATIONAL_DEX_CHIMCHAR 331
#define NATIONAL_DEX_MONFERNO 332
#define NATIONAL_DEX_INFERNAPE 333
#define NATIONAL_DEX_PIPLUP 334
#define NATIONAL_DEX_PRINPLUP 335
#define NATIONAL_DEX_EMPOLEON 336
#define NATIONAL_DEX_SNIVY 337
#define NATIONAL_DEX_SERVINE 338
#define NATIONAL_DEX_SERPERIOR 339
#define NATIONAL_DEX_TEPIG 340
#define NATIONAL_DEX_PIGNITE 341
#define NATIONAL_DEX_EMBOAR 342
#define NATIONAL_DEX_OSHAWOTT 343
#define NATIONAL_DEX_DEWOTT 344
#define NATIONAL_DEX_SAMUROTT 345
#define NATIONAL_DEX_CHESPIN 346
#define NATIONAL_DEX_QUILLADIN 347
#define NATIONAL_DEX_CHESNAUGHT 348
#define NATIONAL_DEX_FENNEKIN 349
#define NATIONAL_DEX_BRAIXEN 350
#define NATIONAL_DEX_DELPHOX 351
#define NATIONAL_DEX_FROAKIE 352
#define NATIONAL_DEX_FROGADIER 353
#define NATIONAL_DEX_GRENINJA 354
#define NATIONAL_DEX_ROWLET 355
#define NATIONAL_DEX_DARTRIX 356
#define NATIONAL_DEX_DECIDUEYE 357
#define NATIONAL_DEX_LITTEN 358
#define NATIONAL_DEX_TORRACAT 359
#define NATIONAL_DEX_INCINEROAR 360
#define NATIONAL_DEX_POPPLIO 361
#define NATIONAL_DEX_BRIONNE 362
#define NATIONAL_DEX_PRIMARINA 363
#define NATIONAL_DEX_GROOKEY 364
#define NATIONAL_DEX_THWACKEY 365
#define NATIONAL_DEX_RILLABOOM 366
#define NATIONAL_DEX_SCORBUNNY 367
#define NATIONAL_DEX_RABOOT 368
#define NATIONAL_DEX_CINDERACE 369
#define NATIONAL_DEX_SOBBLE 370
#define NATIONAL_DEX_DRIZZILE 371
#define NATIONAL_DEX_INTELEON 372
#define NATIONAL_DEX_COSMOG 373
#define NATIONAL_DEX_COSMOEM 374
#define NATIONAL_DEX_SOLGALEO 375
#define NATIONAL_DEX_LUNALA 376
#define NATIONAL_DEX_NIHILEGO 377
#define NATIONAL_DEX_BUZZWOLE 378
#define NATIONAL_DEX_PHEROMOSA 379
#define NATIONAL_DEX_XURKITREE 380
#define NATIONAL_DEX_CELESTEELA 381
#define NATIONAL_DEX_KARTANA 382
#define NATIONAL_DEX_GUZZLORD 383
#define NATIONAL_DEX_NECROZMA 384
#define NATIONAL_DEX_POIPOLE 385
#define NATIONAL_DEX_NAGANADEL 386
#define NATIONAL_DEX_STAKATAKA 387
#define NATIONAL_DEX_BLACEPHALON 388
#define NATIONAL_DEX_TYPE_NULL 389
#define NATIONAL_DEX_SILVALLY 390

// Divergent pokemon exist in a separate dex. They are ordered after the base set so that they are present in the game
// with meaningful pokedex orders defined in Pokedex_Orders.c
#define NATIONAL_DIVERGENT_DEX_ZIGZAGOON 391 // 1
#define NATIONAL_DIVERGENT_DEX_LINOONE 392 // 2
#define NATIONAL_DIVERGENT_DEX_OBSTAGOON 393 // 3
#define NATIONAL_DIVERGENT_DEX_STARLY 394 // 4
#define NATIONAL_DIVERGENT_DEX_STARAVIA 395 // 5
#define NATIONAL_DIVERGENT_DEX_STARAPTOR 396 // 6
#define NATIONAL_DIVERGENT_DEX_CLOBBOPUS 397 // 7
#define NATIONAL_DIVERGENT_DEX_GRAPPLOCT 398 // 8
#define NATIONAL_DIVERGENT_DEX_KRICKETOT 399 // 9
#define NATIONAL_DIVERGENT_DEX_KRICKETUNE 400 // 10
#define NATIONAL_DIVERGENT_DEX_SPINARAK 401 // 11
#define NATIONAL_DIVERGENT_DEX_ARIADOS 402 // 12
#define NATIONAL_DIVERGENT_DEX_WOOPER 403 // 13
#define NATIONAL_DIVERGENT_DEX_QUAGSIRE 404 // 14
#define NATIONAL_DIVERGENT_DEX_SHINX 405 // 15
#define NATIONAL_DIVERGENT_DEX_LUXIO 406 // 16
#define NATIONAL_DIVERGENT_DEX_LUXRAY 407 // 17
#define NATIONAL_DIVERGENT_DEX_AZURILL 408 // 18
#define NATIONAL_DIVERGENT_DEX_MARILL 409 // 19
#define NATIONAL_DIVERGENT_DEX_AZUMARILL 410 // 20
#define NATIONAL_DIVERGENT_DEX_CLEFFA 411 // 21
#define NATIONAL_DIVERGENT_DEX_CLEFAIRY 412 // 22
#define NATIONAL_DIVERGENT_DEX_CLEFABLE 413 // 23
#define NATIONAL_DIVERGENT_DEX_CHEWTLE 414 // 24
#define NATIONAL_DIVERGENT_DEX_DREDNAW 415 // 25
#define NATIONAL_DIVERGENT_DEX_BOUNSWEET 416 // 26
#define NATIONAL_DIVERGENT_DEX_STEENEE 417 // 27
#define NATIONAL_DIVERGENT_DEX_TSAREENA 418 // 28
#define NATIONAL_DIVERGENT_DEX_WOOBAT 419 // 29
#define NATIONAL_DIVERGENT_DEX_SWOOBAT 420 // 30
#define NATIONAL_DIVERGENT_DEX_DIGLETT 421 // 31
#define NATIONAL_DIVERGENT_DEX_DUGTRIO 422 // 32
#define NATIONAL_DIVERGENT_DEX_DEWPIDER 423 // 33
#define NATIONAL_DIVERGENT_DEX_ARAQUANID 424 // 34
#define NATIONAL_DIVERGENT_DEX_FOMANTIS 425 // 35
#define NATIONAL_DIVERGENT_DEX_LURANTIS 426 // 36
#define NATIONAL_DIVERGENT_DEX_SENTRET 427 // 37
#define NATIONAL_DIVERGENT_DEX_FURRET 428 // 38
#define NATIONAL_DIVERGENT_DEX_POLIWAG 429 // 39
#define NATIONAL_DIVERGENT_DEX_POLIWHIRL 430 // 40
#define NATIONAL_DIVERGENT_DEX_POLIWRATH 431 // 41
#define NATIONAL_DIVERGENT_DEX_POLITOED 432 // 42
#define NATIONAL_DIVERGENT_DEX_HOPPIP 433 // 43
#define NATIONAL_DIVERGENT_DEX_SKIPLOOM 434 // 44
#define NATIONAL_DIVERGENT_DEX_JUMPLUFF 435 // 45
#define NATIONAL_DIVERGENT_DEX_SEWADDLE 436 // 46
#define NATIONAL_DIVERGENT_DEX_SWADLOON 437 // 47
#define NATIONAL_DIVERGENT_DEX_LEAVANNY 438 // 48
#define NATIONAL_DIVERGENT_DEX_WEEDLE 439 // 49
#define NATIONAL_DIVERGENT_DEX_KAKUNA 440 // 50
#define NATIONAL_DIVERGENT_DEX_BEEDRILL 441 // 51
#define NATIONAL_DIVERGENT_DEX_CATERPIE 442 // 52
#define NATIONAL_DIVERGENT_DEX_METAPOD 443 // 53
#define NATIONAL_DIVERGENT_DEX_BUTTERFREE 444 // 54
#define NATIONAL_DIVERGENT_DEX_PANSAGE 445 // 55
#define NATIONAL_DIVERGENT_DEX_SIMISAGE 446 // 56
#define NATIONAL_DIVERGENT_DEX_BUNNELBY 447 // 57
#define NATIONAL_DIVERGENT_DEX_DIGGERSBY 448 // 58
#define NATIONAL_DIVERGENT_DEX_DRIFLOON 449 // 59
#define NATIONAL_DIVERGENT_DEX_DRIFBLIM 450 // 60
#define NATIONAL_DIVERGENT_DEX_MEDITITE 451 // 61
#define NATIONAL_DIVERGENT_DEX_MEDICHAM 452 // 62
#define NATIONAL_DIVERGENT_DEX_MAKUHITA 453 // 63
#define NATIONAL_DIVERGENT_DEX_HARIYAMA 454 // 64
#define NATIONAL_DIVERGENT_DEX_PIDGEY 455 // 65
#define NATIONAL_DIVERGENT_DEX_PIDGEOTTO 456 // 66
#define NATIONAL_DIVERGENT_DEX_PIDGEOT 457 // 67
#define NATIONAL_DIVERGENT_DEX_BLITZLE 458 // 68
#define NATIONAL_DIVERGENT_DEX_ZEBSTRIKA 459 // 69
#define NATIONAL_DIVERGENT_DEX_DUCKLETT 460 // 70
#define NATIONAL_DIVERGENT_DEX_SWANNA 461 // 71
#define NATIONAL_DIVERGENT_DEX_MILCERY 462 // 72
#define NATIONAL_DIVERGENT_DEX_ALCREMIE 463 // 73
#define NATIONAL_DIVERGENT_DEX_SILICOBRA 464 // 74
#define NATIONAL_DIVERGENT_DEX_SANDACONDA 465 // 75
#define NATIONAL_DIVERGENT_DEX_MARACTUS 466 // 76
#define NATIONAL_DIVERGENT_DEX_DWEBBLE 467 // 77
#define NATIONAL_DIVERGENT_DEX_CRUSTLE 468 // 78
#define NATIONAL_DIVERGENT_DEX_BALTOY 469 // 79
#define NATIONAL_DIVERGENT_DEX_CLAYDOL 470 // 80
#define NATIONAL_DIVERGENT_DEX_SKORUPI 471 // 81
#define NATIONAL_DIVERGENT_DEX_DRAPION 472 // 82
#define NATIONAL_DIVERGENT_DEX_MACHOP 473 // 83
#define NATIONAL_DIVERGENT_DEX_MACHOKE 474 // 84
#define NATIONAL_DIVERGENT_DEX_MACHAMP 475 // 85
#define NATIONAL_DIVERGENT_DEX_ABRA 476 // 86
#define NATIONAL_DIVERGENT_DEX_KADABRA 477 // 87
#define NATIONAL_DIVERGENT_DEX_ALAKAZAM 478 // 88
#define NATIONAL_DIVERGENT_DEX_SNUBBULL 479 // 89
#define NATIONAL_DIVERGENT_DEX_GRANBULL 480 // 90
#define NATIONAL_DIVERGENT_DEX_MEOWTH 481 // 91
#define NATIONAL_DIVERGENT_DEX_PERRSERKER 482 // 92
#define NATIONAL_DIVERGENT_DEX_SOLOSIS 483 // 93
#define NATIONAL_DIVERGENT_DEX_DUOSION 484 // 94
#define NATIONAL_DIVERGENT_DEX_REUNICLUS 485 // 95
#define NATIONAL_DIVERGENT_DEX_NATU 486 // 96
#define NATIONAL_DIVERGENT_DEX_XATU 487 // 97
#define NATIONAL_DIVERGENT_DEX_TYNAMO 488 // 98
#define NATIONAL_DIVERGENT_DEX_EELEKTRIK 489 // 99
#define NATIONAL_DIVERGENT_DEX_EELEKTROSS 490 // 100
#define NATIONAL_DIVERGENT_DEX_LARVITAR 491 // 101
#define NATIONAL_DIVERGENT_DEX_PUPITAR 492 // 102
#define NATIONAL_DIVERGENT_DEX_TYRANITAR 493 // 103
#define NATIONAL_DIVERGENT_DEX_MAGNEMITE 494 // 104
#define NATIONAL_DIVERGENT_DEX_MAGNETON 495 // 105
#define NATIONAL_DIVERGENT_DEX_MAGNEZONE 496 // 106
#define NATIONAL_DIVERGENT_DEX_ARON 497 // 107
#define NATIONAL_DIVERGENT_DEX_LAIRON 498 // 108
#define NATIONAL_DIVERGENT_DEX_AGGRON 499 // 109
#define NATIONAL_DIVERGENT_DEX_VANILLITE 500 // 110
#define NATIONAL_DIVERGENT_DEX_VANILLISH 501 // 111
#define NATIONAL_DIVERGENT_DEX_VANILLUXE 502 // 112
#define NATIONAL_DIVERGENT_DEX_SPHEAL 503 // 113
#define NATIONAL_DIVERGENT_DEX_SEALEO 504 // 114
#define NATIONAL_DIVERGENT_DEX_WALREIN 505 // 115
#define NATIONAL_DIVERGENT_DEX_GEODUDE 506 // 116
#define NATIONAL_DIVERGENT_DEX_GRAVELER 507 // 117
#define NATIONAL_DIVERGENT_DEX_GOLEM 508 // 118
#define NATIONAL_DIVERGENT_DEX_SMOOCHUM 509 // 119
#define NATIONAL_DIVERGENT_DEX_JYNX 510 // 120
#define NATIONAL_DIVERGENT_DEX_SANDSHREW 511 // 121
#define NATIONAL_DIVERGENT_DEX_SANDSLASH 512 // 122
#define NATIONAL_DIVERGENT_DEX_ORICORIO 513 // 123
#define NATIONAL_DIVERGENT_DEX_NUMEL 514 // 124
#define NATIONAL_DIVERGENT_DEX_CAMERUPT 515 // 125
#define NATIONAL_DIVERGENT_DEX_BAGON 516 // 126
#define NATIONAL_DIVERGENT_DEX_SHELGON 517 // 127
#define NATIONAL_DIVERGENT_DEX_SALAMENCE 518 // 128
#define NATIONAL_DIVERGENT_DEX_FEEBAS 519 // 129
#define NATIONAL_DIVERGENT_DEX_MILOTIC 520 // 130
#define NATIONAL_DIVERGENT_DEX_DEERLING 521 // 131
#define NATIONAL_DIVERGENT_DEX_SAWSBUCK 522 // 132
#define NATIONAL_DIVERGENT_DEX_VULPIX 523 // 133
#define NATIONAL_DIVERGENT_DEX_NINETALES 524 // 134
#define NATIONAL_DIVERGENT_DEX_PANSEAR 525 // 135
#define NATIONAL_DIVERGENT_DEX_SIMISEAR 526 // 136
#define NATIONAL_DIVERGENT_DEX_CUBONE 527 // 137
#define NATIONAL_DIVERGENT_DEX_MAROWAK 528 // 138
#define NATIONAL_DIVERGENT_DEX_MAGBY 529 // 139
#define NATIONAL_DIVERGENT_DEX_MAGMAR 530 // 140
#define NATIONAL_DIVERGENT_DEX_MAGMORTAR 531 // 141
#define NATIONAL_DIVERGENT_DEX_PETILIL 532 // 142
#define NATIONAL_DIVERGENT_DEX_LILLIGANT 533 // 143
#define NATIONAL_DIVERGENT_DEX_TOGEDEMARU 534 // 144
#define NATIONAL_DIVERGENT_DEX_APPLIN 535 // 145
#define NATIONAL_DIVERGENT_DEX_FLAPPLE 536 // 146
#define NATIONAL_DIVERGENT_DEX_APPLETUN 537 // 147
#define NATIONAL_DIVERGENT_DEX_ELECTRIKE 538 // 148
#define NATIONAL_DIVERGENT_DEX_MANECTRIC 539 // 149
#define NATIONAL_DIVERGENT_DEX_AUDINO 540 // 150
#define NATIONAL_DIVERGENT_DEX_STUFFUL 541 // 151
#define NATIONAL_DIVERGENT_DEX_BEWEAR 542 // 152
#define NATIONAL_DIVERGENT_DEX_TYROGUE 543 // 153
#define NATIONAL_DIVERGENT_DEX_HITMONLEE 544 // 154
#define NATIONAL_DIVERGENT_DEX_HITMONCHAN 545 // 155
#define NATIONAL_DIVERGENT_DEX_HITMONTOP 546 // 156
#define NATIONAL_DIVERGENT_DEX_TYMPOLE 547 // 157
#define NATIONAL_DIVERGENT_DEX_PALPITOAD 548 // 158
#define NATIONAL_DIVERGENT_DEX_SEISMITOAD 549 // 159
#define NATIONAL_DIVERGENT_DEX_CRAMORANT 550 // 160
#define NATIONAL_DIVERGENT_DEX_ELEKID 551 // 161
#define NATIONAL_DIVERGENT_DEX_ELECTABUZZ 552 // 162
#define NATIONAL_DIVERGENT_DEX_ELECTIVIRE 553 // 163
#define NATIONAL_DIVERGENT_DEX_PANPOUR 554 // 164
#define NATIONAL_DIVERGENT_DEX_SIMIPOUR 555 // 165
#define NATIONAL_DIVERGENT_DEX_WIMPOD 556 // 166
#define NATIONAL_DIVERGENT_DEX_GOLISOPOD 557 // 167
#define NATIONAL_DIVERGENT_DEX_EXEGGCUTE 558 // 168
#define NATIONAL_DIVERGENT_DEX_EXEGGUTOR 559 // 169
#define NATIONAL_DIVERGENT_DEX_NOSEPASS 560 // 170
#define NATIONAL_DIVERGENT_DEX_PROBOPASS 561 // 171
#define NATIONAL_DIVERGENT_DEX_ANORITH 562 // 172
#define NATIONAL_DIVERGENT_DEX_ARMALDO 563 // 173
#define NATIONAL_DIVERGENT_DEX_GULPIN 564 // 174
#define NATIONAL_DIVERGENT_DEX_SWALOT 565 // 175
#define NATIONAL_DIVERGENT_DEX_HAWLUCHA 566 // 176
#define NATIONAL_DIVERGENT_DEX_INDEEDEE 567 // 177
#define NATIONAL_DIVERGENT_DEX_TROPIUS 568 // 178
// DITTO has no divergent dex number - reuses NATIONAL_DEX_DITTO (same number in both modes)
#define NATIONAL_DIVERGENT_DEX_STUNKY 570 // 180
#define NATIONAL_DIVERGENT_DEX_SKUNTANK 571 // 181
#define NATIONAL_DIVERGENT_DEX_PANCHAM 572 // 182
#define NATIONAL_DIVERGENT_DEX_PANGORO 573 // 183
#define NATIONAL_DIVERGENT_DEX_SINISTEA 574 // 184
#define NATIONAL_DIVERGENT_DEX_POLTEAGEIST 575 // 185
#define NATIONAL_DIVERGENT_DEX_KLEFKI 576 // 186
#define NATIONAL_DIVERGENT_DEX_LITWICK 577 // 187
#define NATIONAL_DIVERGENT_DEX_LAMPENT 578 // 188
#define NATIONAL_DIVERGENT_DEX_CHANDELURE 579 // 189
#define NATIONAL_DIVERGENT_DEX_DREEPY 580 // 190
#define NATIONAL_DIVERGENT_DEX_DRAKLOAK 581 // 191
#define NATIONAL_DIVERGENT_DEX_DRAGAPULT 582 // 192
#define NATIONAL_DIVERGENT_DEX_ODDISH 583 // 193
#define NATIONAL_DIVERGENT_DEX_GLOOM 584 // 194
#define NATIONAL_DIVERGENT_DEX_VILEPLUME 585 // 195
#define NATIONAL_DIVERGENT_DEX_BELLOSSOM 586 // 196
#define NATIONAL_DIVERGENT_DEX_GASTLY 587 // 197
#define NATIONAL_DIVERGENT_DEX_HAUNTER 588 // 198
#define NATIONAL_DIVERGENT_DEX_GENGAR 589 // 199
#define NATIONAL_DIVERGENT_DEX_TRUBBISH 590 // 200
#define NATIONAL_DIVERGENT_DEX_GARBODOR 591 // 201
#define NATIONAL_DIVERGENT_DEX_PORYGON 592 // 202
#define NATIONAL_DIVERGENT_DEX_PORYGON2 593 // 203
#define NATIONAL_DIVERGENT_DEX_PORYGON_Z 594 // 204
#define NATIONAL_DIVERGENT_DEX_AIPOM 595 // 205
#define NATIONAL_DIVERGENT_DEX_AMBIPOM 596 // 206
#define NATIONAL_DIVERGENT_DEX_MUNCHLAX 597 // 207
#define NATIONAL_DIVERGENT_DEX_SNORLAX 598 // 208
#define NATIONAL_DIVERGENT_DEX_SMEARGLE 599 // 209
// ROTOM has no divergent dex number - reuses NATIONAL_DEX_ROTOM (same number in both modes)
#define NATIONAL_DIVERGENT_DEX_TANGELA 601 // 211
#define NATIONAL_DIVERGENT_DEX_TANGROWTH 602 // 212
#define NATIONAL_DIVERGENT_DEX_PONYTA 603 // 213
#define NATIONAL_DIVERGENT_DEX_RAPIDASH 604 // 214
#define NATIONAL_DIVERGENT_DEX_SPRITZEE 605 // 215
#define NATIONAL_DIVERGENT_DEX_AROMATISSE 606 // 216
#define NATIONAL_DIVERGENT_DEX_MUNNA 607 // 217
#define NATIONAL_DIVERGENT_DEX_MUSHARNA 608 // 218
#define NATIONAL_DIVERGENT_DEX_GROWLITHE 609 // 219
#define NATIONAL_DIVERGENT_DEX_ARCANINE 610 // 220
#define NATIONAL_DIVERGENT_DEX_GOLETT 611 // 221
#define NATIONAL_DIVERGENT_DEX_GOLURK 612 // 222
#define NATIONAL_DIVERGENT_DEX_BELDUM 613 // 223
#define NATIONAL_DIVERGENT_DEX_METANG 614 // 224
#define NATIONAL_DIVERGENT_DEX_METAGROSS 615 // 225
#define NATIONAL_DIVERGENT_DEX_ONIX 616 // 226
#define NATIONAL_DIVERGENT_DEX_STEELIX 617 // 227
#define NATIONAL_DIVERGENT_DEX_DEINO 618 // 228
#define NATIONAL_DIVERGENT_DEX_ZWEILOUS 619 // 229
#define NATIONAL_DIVERGENT_DEX_HYDREIGON 620 // 230
#define NATIONAL_DIVERGENT_DEX_GLIGAR 621 // 231
#define NATIONAL_DIVERGENT_DEX_GLISCOR 622 // 232
#define NATIONAL_DIVERGENT_DEX_DRAMPA 623 // 233
#define NATIONAL_DIVERGENT_DEX_SPIRITOMB 624 // 234
#define NATIONAL_DIVERGENT_DEX_STARYU 625 // 235
#define NATIONAL_DIVERGENT_DEX_STARMIE 626 // 236
#define NATIONAL_DIVERGENT_DEX_YANMA 627 // 237
#define NATIONAL_DIVERGENT_DEX_YANMEGA 628 // 238
#define NATIONAL_DIVERGENT_DEX_IMPIDIMP 629 // 239
#define NATIONAL_DIVERGENT_DEX_MORGREM 630 // 240
#define NATIONAL_DIVERGENT_DEX_GRIMMSNARL 631 // 241
#define NATIONAL_DIVERGENT_DEX_PHANPY 632 // 242
#define NATIONAL_DIVERGENT_DEX_DONPHAN 633 // 243
#define NATIONAL_DIVERGENT_DEX_RHYHORN 634 // 244
#define NATIONAL_DIVERGENT_DEX_RHYDON 635 // 245
#define NATIONAL_DIVERGENT_DEX_RHYPERIOR 636 // 246
#define NATIONAL_DIVERGENT_DEX_PINSIR 637 // 247
#define NATIONAL_DIVERGENT_DEX_MURKROW 638 // 248
#define NATIONAL_DIVERGENT_DEX_HONCHKROW 639 // 249
#define NATIONAL_DIVERGENT_DEX_HONEDGE 640 // 250
#define NATIONAL_DIVERGENT_DEX_DOUBLADE 641 // 251
#define NATIONAL_DIVERGENT_DEX_AEGISLASH 642 // 252
#define NATIONAL_DIVERGENT_DEX_SWABLU 643 // 253
#define NATIONAL_DIVERGENT_DEX_ALTARIA 644 // 254
#define NATIONAL_DIVERGENT_DEX_DEDENNE 645 // 255
#define NATIONAL_DIVERGENT_DEX_DURANT 646 // 256
#define NATIONAL_DIVERGENT_DEX_HEATMOR 647 // 257
#define NATIONAL_DIVERGENT_DEX_SEEL 648 // 258
#define NATIONAL_DIVERGENT_DEX_DEWGONG 649 // 259
#define NATIONAL_DIVERGENT_DEX_EISCUE 650 // 260
#define NATIONAL_DIVERGENT_DEX_ABSOL 651 // 261
#define NATIONAL_DIVERGENT_DEX_VOLTORB 652 // 262
#define NATIONAL_DIVERGENT_DEX_ELECTRODE 653 // 263
#define NATIONAL_DIVERGENT_DEX_CRYOGONAL 654 // 264
#define NATIONAL_DIVERGENT_DEX_SNOVER 655 // 265
#define NATIONAL_DIVERGENT_DEX_ABOMASNOW 656 // 266
#define NATIONAL_DIVERGENT_DEX_SHUPPET 657 // 267
#define NATIONAL_DIVERGENT_DEX_BANETTE 658 // 268
#define NATIONAL_DIVERGENT_DEX_SKRELP 659 // 269
#define NATIONAL_DIVERGENT_DEX_DRAGALGE 660 // 270
#define NATIONAL_DIVERGENT_DEX_ZANGOOSE 661 // 271
#define NATIONAL_DIVERGENT_DEX_SEVIPER 662 // 272
#define NATIONAL_DIVERGENT_DEX_DRUDDIGON 663 // 273
#define NATIONAL_DIVERGENT_DEX_AERODACTYL 664 // 274
#define NATIONAL_DIVERGENT_DEX_KRABBY 665 // 275
#define NATIONAL_DIVERGENT_DEX_KINGLER 666 // 276
#define NATIONAL_DIVERGENT_DEX_QWILFISH 667 // 277
#define NATIONAL_DIVERGENT_DEX_BARBOACH 668 // 278
#define NATIONAL_DIVERGENT_DEX_WHISCASH 669 // 279
#define NATIONAL_DIVERGENT_DEX_SCYTHER 670 // 280
#define NATIONAL_DIVERGENT_DEX_SCIZOR 671 // 281
#define NATIONAL_DIVERGENT_DEX_WISHIWASHI 672 // 282
#define NATIONAL_DIVERGENT_DEX_ARCTOZOLT 673 // 283
#define NATIONAL_DIVERGENT_DEX_DRACOVISH 674 // 284
#define NATIONAL_DIVERGENT_DEX_BOUFFALANT 675 // 285
#define NATIONAL_DIVERGENT_DEX_KUBFU 676 // 286
#define NATIONAL_DIVERGENT_DEX_URSHIFU 677 // 287
#define NATIONAL_DIVERGENT_DEX_TORNADUS 678 // 288
#define NATIONAL_DIVERGENT_DEX_THUNDURUS 679 // 289
#define NATIONAL_DIVERGENT_DEX_LANDORUS 680 // 290
// JIRACHI has no divergent dex number - reuses NATIONAL_DEX_JIRACHI (same number in both modes)
#define NATIONAL_DIVERGENT_DEX_XERNEAS 682 // 292
#define NATIONAL_DIVERGENT_DEX_LUGIA 683 // 293
#define NATIONAL_DIVERGENT_DEX_HOOPA 684 // 294
#define NATIONAL_DIVERGENT_DEX_HEATRAN 685 // 295
#define NATIONAL_DIVERGENT_DEX_ZARUDE 686 // 296
#define NATIONAL_DIVERGENT_DEX_SPECTRIER 687 // 297
#define NATIONAL_DIVERGENT_DEX_GENESECT 688 // 298
#define NATIONAL_DIVERGENT_DEX_DARKRAI 689 // 299
// VICTINI has no divergent dex number - reuses NATIONAL_DEX_VICTINI (same number in both modes)
// No need to replicate the starter and UB list here because the list above is just for pokemon that differ
// Rotom & Ditto are duplicated for ease of readability

// PERSIAN is not in the divergent dex, but needs it's own dedicated pokedex entry so it can be registered
// as seen/caught when swarming, as well as have a dex entry separate from Perrserker.
// This does not have an impact on the 390 catchable pokemon in divergent mode; Perrsian doesn't appear in the dex count
#define NATIONAL_DIVERGENT_DEX_PERSIAN 690

#define FINAL_DEX_ENTRY NATIONAL_DEX_SILVALLY //Not +1 b/c used like this for some asm
#define NATIONAL_DEX_COUNT FINAL_DEX_ENTRY + 1

// Backing-store size for gPokedexEntries. It must cover the divergent storage range (391-690)
// so divergent-mode entry data can be looked up by national dex number. This does NOT change
// the visible dex size, which stays 390 via FINAL_DEX_ENTRY / gNumDexEntries.
#define FINAL_DIVERGENT_DEX_ENTRY NATIONAL_DIVERGENT_DEX_PERSIAN
#define DIVERGENT_DEX_COUNT (FINAL_DIVERGENT_DEX_ENTRY + 1)

extern const u8 DEX_ENTRY_TURTWIG[];
extern const u8 DEX_ENTRY_GROTLE[];
extern const u8 DEX_ENTRY_TORTERRA[];
extern const u8 DEX_ENTRY_CHIMCHAR[];
extern const u8 DEX_ENTRY_MONFERNO[];
extern const u8 DEX_ENTRY_INFERNAPE[];
extern const u8 DEX_ENTRY_PIPLUP[];
extern const u8 DEX_ENTRY_PRINPLUP[];
extern const u8 DEX_ENTRY_EMPOLEON[];
extern const u8 DEX_ENTRY_STARLY[];
extern const u8 DEX_ENTRY_STARAVIA[];
extern const u8 DEX_ENTRY_STARAPTOR[];
extern const u8 DEX_ENTRY_BIDOOF[];
extern const u8 DEX_ENTRY_BIBAREL[];
extern const u8 DEX_ENTRY_KRICKETOT[];
extern const u8 DEX_ENTRY_KRICKETUNE[];
extern const u8 DEX_ENTRY_SHINX[];
extern const u8 DEX_ENTRY_LUXIO[];
extern const u8 DEX_ENTRY_LUXRAY[];
extern const u8 DEX_ENTRY_BUDEW[];
extern const u8 DEX_ENTRY_ROSERADE[];
extern const u8 DEX_ENTRY_SHIELDON[];
extern const u8 DEX_ENTRY_BASTIODON[];
extern const u8 DEX_ENTRY_COMBEE[];
extern const u8 DEX_ENTRY_VESPIQUEN[];
extern const u8 DEX_ENTRY_PACHIRISU[];
extern const u8 DEX_ENTRY_SHELLOS[];
extern const u8 DEX_ENTRY_GASTRODON[];
extern const u8 DEX_ENTRY_AMBIPOM[];
extern const u8 DEX_ENTRY_DRIFLOON[];
extern const u8 DEX_ENTRY_DRIFBLIM[];
extern const u8 DEX_ENTRY_BUNEARY[];
extern const u8 DEX_ENTRY_LOPUNNY[];
extern const u8 DEX_ENTRY_MISMAGIUS[];
extern const u8 DEX_ENTRY_HONCHKROW[];
extern const u8 DEX_ENTRY_STUNKY[];
extern const u8 DEX_ENTRY_SKUNTANK[];
extern const u8 DEX_ENTRY_BONSLY[];
extern const u8 DEX_ENTRY_MIME_JR[];
extern const u8 DEX_ENTRY_HAPPINY[];
extern const u8 DEX_ENTRY_SPIRITOMB[];
extern const u8 DEX_ENTRY_GIBLE[];
extern const u8 DEX_ENTRY_GABITE[];
extern const u8 DEX_ENTRY_GARCHOMP[];
extern const u8 DEX_ENTRY_MUNCHLAX[];
extern const u8 DEX_ENTRY_RIOLU[];
extern const u8 DEX_ENTRY_LUCARIO[];
extern const u8 DEX_ENTRY_HIPPOPOTAS[];
extern const u8 DEX_ENTRY_HIPPOWDON[];
extern const u8 DEX_ENTRY_SKORUPI[];
extern const u8 DEX_ENTRY_DRAPION[];
extern const u8 DEX_ENTRY_CROAGUNK[];
extern const u8 DEX_ENTRY_TOXICROAK[];
extern const u8 DEX_ENTRY_CARNIVINE[];
extern const u8 DEX_ENTRY_SNOVER[];
extern const u8 DEX_ENTRY_ABOMASNOW[];
extern const u8 DEX_ENTRY_WEAVILE[];
extern const u8 DEX_ENTRY_MAGNEZONE[];
extern const u8 DEX_ENTRY_RHYPERIOR[];
extern const u8 DEX_ENTRY_TANGROWTH[];
extern const u8 DEX_ENTRY_ELECTIVIRE[];
extern const u8 DEX_ENTRY_MAGMORTAR[];
extern const u8 DEX_ENTRY_TOGEKISS[];
extern const u8 DEX_ENTRY_YANMEGA[];
extern const u8 DEX_ENTRY_LEAFEON[];
extern const u8 DEX_ENTRY_GLACEON[];
extern const u8 DEX_ENTRY_GLISCOR[];
extern const u8 DEX_ENTRY_MAMOSWINE[];
extern const u8 DEX_ENTRY_PORYGON_Z[];
extern const u8 DEX_ENTRY_GALLADE[];
extern const u8 DEX_ENTRY_PROBOPASS[];
extern const u8 DEX_ENTRY_DUSKNOIR[];
extern const u8 DEX_ENTRY_FROSLASS[];
extern const u8 DEX_ENTRY_ROTOM[];
extern const u8 DEX_ENTRY_HEATRAN[];
extern const u8 DEX_ENTRY_DARKRAI[];
extern const u8 DEX_ENTRY_SHAYMIN[];
extern const u8 DEX_ENTRY_VICTINI[];
extern const u8 DEX_ENTRY_SNIVY[];
extern const u8 DEX_ENTRY_SERVINE[];
extern const u8 DEX_ENTRY_SERPERIOR[];
extern const u8 DEX_ENTRY_TEPIG[];
extern const u8 DEX_ENTRY_PIGNITE[];
extern const u8 DEX_ENTRY_EMBOAR[];
extern const u8 DEX_ENTRY_OSHAWOTT[];
extern const u8 DEX_ENTRY_DEWOTT[];
extern const u8 DEX_ENTRY_SAMUROTT[];
extern const u8 DEX_ENTRY_LILLIPUP[];
extern const u8 DEX_ENTRY_HERDIER[];
extern const u8 DEX_ENTRY_STOUTLAND[];
extern const u8 DEX_ENTRY_PANSAGE[];
extern const u8 DEX_ENTRY_SIMISAGE[];
extern const u8 DEX_ENTRY_PANSEAR[];
extern const u8 DEX_ENTRY_SIMISEAR[];
extern const u8 DEX_ENTRY_PANPOUR[];
extern const u8 DEX_ENTRY_SIMIPOUR[];
extern const u8 DEX_ENTRY_MUNNA[];
extern const u8 DEX_ENTRY_MUSHARNA[];
extern const u8 DEX_ENTRY_BLITZLE[];
extern const u8 DEX_ENTRY_ZEBSTRIKA[];
extern const u8 DEX_ENTRY_ROGGENROLA[];
extern const u8 DEX_ENTRY_BOLDORE[];
extern const u8 DEX_ENTRY_GIGALITH[];
extern const u8 DEX_ENTRY_WOOBAT[];
extern const u8 DEX_ENTRY_SWOOBAT[];
extern const u8 DEX_ENTRY_DRILBUR[];
extern const u8 DEX_ENTRY_EXCADRILL[];
extern const u8 DEX_ENTRY_AUDINO[];
extern const u8 DEX_ENTRY_TIMBURR[];
extern const u8 DEX_ENTRY_GURDURR[];
extern const u8 DEX_ENTRY_CONKELDURR[];
extern const u8 DEX_ENTRY_TYMPOLE[];
extern const u8 DEX_ENTRY_PALPITOAD[];
extern const u8 DEX_ENTRY_SEISMITOAD[];
extern const u8 DEX_ENTRY_SEWADDLE[];
extern const u8 DEX_ENTRY_SWADLOON[];
extern const u8 DEX_ENTRY_LEAVANNY[];
extern const u8 DEX_ENTRY_VENIPEDE[];
extern const u8 DEX_ENTRY_WHIRLIPEDE[];
extern const u8 DEX_ENTRY_SCOLIPEDE[];
extern const u8 DEX_ENTRY_COTTONEE[];
extern const u8 DEX_ENTRY_WHIMSICOTT[];
extern const u8 DEX_ENTRY_PETILIL[];
extern const u8 DEX_ENTRY_LILLIGANT[];
extern const u8 DEX_ENTRY_SANDILE[];
extern const u8 DEX_ENTRY_KROKOROK[];
extern const u8 DEX_ENTRY_KROOKODILE[];
extern const u8 DEX_ENTRY_DARUMAKA[];
extern const u8 DEX_ENTRY_DARMANITAN[];
extern const u8 DEX_ENTRY_MARACTUS[];
extern const u8 DEX_ENTRY_DWEBBLE[];
extern const u8 DEX_ENTRY_CRUSTLE[];
extern const u8 DEX_ENTRY_SCRAGGY[];
extern const u8 DEX_ENTRY_SCRAFTY[];
extern const u8 DEX_ENTRY_YAMASK[];
extern const u8 DEX_ENTRY_COFAGRIGUS[];
extern const u8 DEX_ENTRY_TRUBBISH[];
extern const u8 DEX_ENTRY_GARBODOR[];
extern const u8 DEX_ENTRY_ZORUA[];
extern const u8 DEX_ENTRY_ZOROARK[];
extern const u8 DEX_ENTRY_SOLOSIS[];
extern const u8 DEX_ENTRY_DUOSION[];
extern const u8 DEX_ENTRY_REUNICLUS[];
extern const u8 DEX_ENTRY_DUCKLETT[];
extern const u8 DEX_ENTRY_SWANNA[];
extern const u8 DEX_ENTRY_VANILLITE[];
extern const u8 DEX_ENTRY_VANILLISH[];
extern const u8 DEX_ENTRY_VANILLUXE[];
extern const u8 DEX_ENTRY_DEERLING[];
extern const u8 DEX_ENTRY_SAWSBUCK[];
extern const u8 DEX_ENTRY_EMOLGA[];
extern const u8 DEX_ENTRY_FOONGUS[];
extern const u8 DEX_ENTRY_AMOONGUSS[];
extern const u8 DEX_ENTRY_FRILLISH[];
extern const u8 DEX_ENTRY_JELLICENT[];
extern const u8 DEX_ENTRY_JOLTIK[];
extern const u8 DEX_ENTRY_GALVANTULA[];
extern const u8 DEX_ENTRY_FERROSEED[];
extern const u8 DEX_ENTRY_FERROTHORN[];
extern const u8 DEX_ENTRY_KLINK[];
extern const u8 DEX_ENTRY_KLANG[];
extern const u8 DEX_ENTRY_KLINKLANG[];
extern const u8 DEX_ENTRY_TYNAMO[];
extern const u8 DEX_ENTRY_EELEKTRIK[];
extern const u8 DEX_ENTRY_EELEKTROSS[];
extern const u8 DEX_ENTRY_ELGYEM[];
extern const u8 DEX_ENTRY_BEHEEYEM[];
extern const u8 DEX_ENTRY_LITWICK[];
extern const u8 DEX_ENTRY_LAMPENT[];
extern const u8 DEX_ENTRY_CHANDELURE[];
extern const u8 DEX_ENTRY_CUBCHOO[];
extern const u8 DEX_ENTRY_BEARTIC[];
extern const u8 DEX_ENTRY_CRYOGONAL[];
extern const u8 DEX_ENTRY_STUNFISK[];
extern const u8 DEX_ENTRY_MIENFOO[];
extern const u8 DEX_ENTRY_MIENSHAO[];
extern const u8 DEX_ENTRY_DRUDDIGON[];
extern const u8 DEX_ENTRY_GOLETT[];
extern const u8 DEX_ENTRY_GOLURK[];
extern const u8 DEX_ENTRY_PAWNIARD[];
extern const u8 DEX_ENTRY_BISHARP[];
extern const u8 DEX_ENTRY_BOUFFALANT[];
extern const u8 DEX_ENTRY_VULLABY[];
extern const u8 DEX_ENTRY_MANDIBUZZ[];
extern const u8 DEX_ENTRY_HEATMOR[];
extern const u8 DEX_ENTRY_DURANT[];
extern const u8 DEX_ENTRY_DEINO[];
extern const u8 DEX_ENTRY_ZWEILOUS[];
extern const u8 DEX_ENTRY_HYDREIGON[];
extern const u8 DEX_ENTRY_LARVESTA[];
extern const u8 DEX_ENTRY_VOLCARONA[];
extern const u8 DEX_ENTRY_TORNADUS[];
extern const u8 DEX_ENTRY_THUNDURUS[];
extern const u8 DEX_ENTRY_LANDORUS[];
extern const u8 DEX_ENTRY_GENESECT[];
extern const u8 DEX_ENTRY_CHESPIN[];
extern const u8 DEX_ENTRY_QUILLADIN[];
extern const u8 DEX_ENTRY_CHESNAUGHT[];
extern const u8 DEX_ENTRY_FENNEKIN[];
extern const u8 DEX_ENTRY_BRAIXEN[];
extern const u8 DEX_ENTRY_DELPHOX[];
extern const u8 DEX_ENTRY_FROAKIE[];
extern const u8 DEX_ENTRY_FROGADIER[];
extern const u8 DEX_ENTRY_GRENINJA[];
extern const u8 DEX_ENTRY_BUNNELBY[];
extern const u8 DEX_ENTRY_DIGGERSBY[];
extern const u8 DEX_ENTRY_FLETCHLING[];
extern const u8 DEX_ENTRY_FLETCHINDER[];
extern const u8 DEX_ENTRY_TALONFLAME[];
extern const u8 DEX_ENTRY_LITLEO[];
extern const u8 DEX_ENTRY_PYROAR[];
extern const u8 DEX_ENTRY_FLABEBE[];
extern const u8 DEX_ENTRY_FLOETTE[];
extern const u8 DEX_ENTRY_FLORGES[];
extern const u8 DEX_ENTRY_SKIDDO[];
extern const u8 DEX_ENTRY_GOGOAT[];
extern const u8 DEX_ENTRY_PANCHAM[];
extern const u8 DEX_ENTRY_PANGORO[];
extern const u8 DEX_ENTRY_HONEDGE[];
extern const u8 DEX_ENTRY_DOUBLADE[];
extern const u8 DEX_ENTRY_AEGISLASH[];
extern const u8 DEX_ENTRY_SPRITZEE[];
extern const u8 DEX_ENTRY_AROMATISSE[];
extern const u8 DEX_ENTRY_INKAY[];
extern const u8 DEX_ENTRY_MALAMAR[];
extern const u8 DEX_ENTRY_BINACLE[];
extern const u8 DEX_ENTRY_BARBARACLE[];
extern const u8 DEX_ENTRY_SKRELP[];
extern const u8 DEX_ENTRY_DRAGALGE[];
extern const u8 DEX_ENTRY_HELIOPTILE[];
extern const u8 DEX_ENTRY_HELIOLISK[];
extern const u8 DEX_ENTRY_TYRUNT[];
extern const u8 DEX_ENTRY_TYRANTRUM[];
extern const u8 DEX_ENTRY_AMAURA[];
extern const u8 DEX_ENTRY_AURORUS[];
extern const u8 DEX_ENTRY_SYLVEON[];
extern const u8 DEX_ENTRY_HAWLUCHA[];
extern const u8 DEX_ENTRY_DEDENNE[];
extern const u8 DEX_ENTRY_CARBINK[];
extern const u8 DEX_ENTRY_GOOMY[];
extern const u8 DEX_ENTRY_SLIGGOO[];
extern const u8 DEX_ENTRY_GOODRA[];
extern const u8 DEX_ENTRY_KLEFKI[];
extern const u8 DEX_ENTRY_PHANTUMP[];
extern const u8 DEX_ENTRY_TREVENANT[];
extern const u8 DEX_ENTRY_BERGMITE[];
extern const u8 DEX_ENTRY_AVALUGG[];
extern const u8 DEX_ENTRY_NOIBAT[];
extern const u8 DEX_ENTRY_NOIVERN[];
extern const u8 DEX_ENTRY_XERNEAS[];
extern const u8 DEX_ENTRY_HOOPA[];
extern const u8 DEX_ENTRY_VOLCANION[];
extern const u8 DEX_ENTRY_ROWLET[];
extern const u8 DEX_ENTRY_DARTRIX[];
extern const u8 DEX_ENTRY_DECIDUEYE[];
extern const u8 DEX_ENTRY_LITTEN[];
extern const u8 DEX_ENTRY_TORRACAT[];
extern const u8 DEX_ENTRY_INCINEROAR[];
extern const u8 DEX_ENTRY_POPPLIO[];
extern const u8 DEX_ENTRY_BRIONNE[];
extern const u8 DEX_ENTRY_PRIMARINA[];
extern const u8 DEX_ENTRY_PIKIPEK[];
extern const u8 DEX_ENTRY_TRUMBEAK[];
extern const u8 DEX_ENTRY_TOUCANNON[];
extern const u8 DEX_ENTRY_GRUBBIN[];
extern const u8 DEX_ENTRY_CHARJABUG[];
extern const u8 DEX_ENTRY_VIKAVOLT[];
extern const u8 DEX_ENTRY_CRABRAWLER[];
extern const u8 DEX_ENTRY_CRABOMINABLE[];
extern const u8 DEX_ENTRY_ORICORIO[];
extern const u8 DEX_ENTRY_CUTIEFLY[];
extern const u8 DEX_ENTRY_RIBOMBEE[];
extern const u8 DEX_ENTRY_ROCKRUFF[];
extern const u8 DEX_ENTRY_LYCANROC[];
extern const u8 DEX_ENTRY_WISHIWASHI[];
extern const u8 DEX_ENTRY_MAREANIE[];
extern const u8 DEX_ENTRY_TOXAPEX[];
extern const u8 DEX_ENTRY_MUDBRAY[];
extern const u8 DEX_ENTRY_MUDSDALE[];
extern const u8 DEX_ENTRY_DEWPIDER[];
extern const u8 DEX_ENTRY_ARAQUANID[];
extern const u8 DEX_ENTRY_FOMANTIS[];
extern const u8 DEX_ENTRY_LURANTIS[];
extern const u8 DEX_ENTRY_MORELULL[];
extern const u8 DEX_ENTRY_SHIINOTIC[];
extern const u8 DEX_ENTRY_SALANDIT[];
extern const u8 DEX_ENTRY_SALAZZLE[];
extern const u8 DEX_ENTRY_STUFFUL[];
extern const u8 DEX_ENTRY_BEWEAR[];
extern const u8 DEX_ENTRY_BOUNSWEET[];
extern const u8 DEX_ENTRY_STEENEE[];
extern const u8 DEX_ENTRY_TSAREENA[];
extern const u8 DEX_ENTRY_COMFEY[];
extern const u8 DEX_ENTRY_ORANGURU[];
extern const u8 DEX_ENTRY_PASSIMIAN[];
extern const u8 DEX_ENTRY_WIMPOD[];
extern const u8 DEX_ENTRY_GOLISOPOD[];
extern const u8 DEX_ENTRY_SANDYGAST[];
extern const u8 DEX_ENTRY_PALOSSAND[];
extern const u8 DEX_ENTRY_TYPE_NULL[];
extern const u8 DEX_ENTRY_SILVALLY[];
extern const u8 DEX_ENTRY_MINIOR[];
extern const u8 DEX_ENTRY_TURTONATOR[];
extern const u8 DEX_ENTRY_TOGEDEMARU[];
extern const u8 DEX_ENTRY_MIMIKYU[];
extern const u8 DEX_ENTRY_DRAMPA[];
extern const u8 DEX_ENTRY_DHELMISE[];
extern const u8 DEX_ENTRY_JANGMO_O[];
extern const u8 DEX_ENTRY_HAKAMO_O[];
extern const u8 DEX_ENTRY_KOMMO_O[];
extern const u8 DEX_ENTRY_COSMOG[];
extern const u8 DEX_ENTRY_COSMOEM[];
extern const u8 DEX_ENTRY_SOLGALEO[];
extern const u8 DEX_ENTRY_LUNALA[];
extern const u8 DEX_ENTRY_NIHILEGO[];
extern const u8 DEX_ENTRY_BUZZWOLE[];
extern const u8 DEX_ENTRY_PHEROMOSA[];
extern const u8 DEX_ENTRY_XURKITREE[];
extern const u8 DEX_ENTRY_CELESTEELA[];
extern const u8 DEX_ENTRY_KARTANA[];
extern const u8 DEX_ENTRY_GUZZLORD[];
extern const u8 DEX_ENTRY_NECROZMA[];
extern const u8 DEX_ENTRY_POIPOLE[];
extern const u8 DEX_ENTRY_NAGANADEL[];
extern const u8 DEX_ENTRY_STAKATAKA[];
extern const u8 DEX_ENTRY_BLACEPHALON[];
extern const u8 DEX_ENTRY_ZERAORA[];
extern const u8 DEX_ENTRY_MELTAN[];
extern const u8 DEX_ENTRY_MELMETAL[];
extern const u8 DEX_ENTRY_GROOKEY[];
extern const u8 DEX_ENTRY_THWACKEY[];
extern const u8 DEX_ENTRY_RILLABOOM[];
extern const u8 DEX_ENTRY_SCORBUNNY[];
extern const u8 DEX_ENTRY_RABOOT[];
extern const u8 DEX_ENTRY_CINDERACE[];
extern const u8 DEX_ENTRY_SOBBLE[];
extern const u8 DEX_ENTRY_DRIZZILE[];
extern const u8 DEX_ENTRY_INTELEON[];
extern const u8 DEX_ENTRY_ROOKIDEE[];
extern const u8 DEX_ENTRY_CORVISQUIRE[];
extern const u8 DEX_ENTRY_CORVIKNIGHT[];
extern const u8 DEX_ENTRY_BLIPBUG[];
extern const u8 DEX_ENTRY_DOTTLER[];
extern const u8 DEX_ENTRY_ORBEETLE[];
extern const u8 DEX_ENTRY_NICKIT[];
extern const u8 DEX_ENTRY_THIEVUL[];
extern const u8 DEX_ENTRY_CHEWTLE[];
extern const u8 DEX_ENTRY_DREDNAW[];
extern const u8 DEX_ENTRY_YAMPER[];
extern const u8 DEX_ENTRY_BOLTUND[];
extern const u8 DEX_ENTRY_ROLYCOLY[];
extern const u8 DEX_ENTRY_CARKOL[];
extern const u8 DEX_ENTRY_COALOSSAL[];
extern const u8 DEX_ENTRY_APPLIN[];
extern const u8 DEX_ENTRY_FLAPPLE[];
extern const u8 DEX_ENTRY_APPLETUN[];
extern const u8 DEX_ENTRY_SILICOBRA[];
extern const u8 DEX_ENTRY_SANDACONDA[];
extern const u8 DEX_ENTRY_CRAMORANT[];
extern const u8 DEX_ENTRY_TOXEL[];
extern const u8 DEX_ENTRY_TOXTRICITY[];
extern const u8 DEX_ENTRY_SIZZLIPEDE[];
extern const u8 DEX_ENTRY_CENTISKORCH[];
extern const u8 DEX_ENTRY_CLOBBOPUS[];
extern const u8 DEX_ENTRY_GRAPPLOCT[];
extern const u8 DEX_ENTRY_SINISTEA[];
extern const u8 DEX_ENTRY_POLTEAGEIST[];
extern const u8 DEX_ENTRY_HATENNA[];
extern const u8 DEX_ENTRY_HATTREM[];
extern const u8 DEX_ENTRY_HATTERENE[];
extern const u8 DEX_ENTRY_IMPIDIMP[];
extern const u8 DEX_ENTRY_MORGREM[];
extern const u8 DEX_ENTRY_GRIMMSNARL[];
extern const u8 DEX_ENTRY_OBSTAGOON[];
extern const u8 DEX_ENTRY_PERRSERKER[];
extern const u8 DEX_ENTRY_CURSOLA[];
extern const u8 DEX_ENTRY_SIRFETCHD[];
extern const u8 DEX_ENTRY_MR_RIME[];
extern const u8 DEX_ENTRY_RUNERIGUS[];
extern const u8 DEX_ENTRY_MILCERY[];
extern const u8 DEX_ENTRY_ALCREMIE_STRAWBERRY[];
extern const u8 DEX_ENTRY_FALINKS[];
extern const u8 DEX_ENTRY_PINCURCHIN[];
extern const u8 DEX_ENTRY_SNOM[];
extern const u8 DEX_ENTRY_FROSMOTH[];
extern const u8 DEX_ENTRY_STONJOURNER[];
extern const u8 DEX_ENTRY_EISCUE[];
extern const u8 DEX_ENTRY_INDEEDEE[];
extern const u8 DEX_ENTRY_MORPEKO[];
extern const u8 DEX_ENTRY_CUFANT[];
extern const u8 DEX_ENTRY_COPPERAJAH[];
extern const u8 DEX_ENTRY_DRACOZOLT[];
extern const u8 DEX_ENTRY_ARCTOZOLT[];
extern const u8 DEX_ENTRY_DRACOVISH[];
extern const u8 DEX_ENTRY_ARCTOVISH[];
extern const u8 DEX_ENTRY_DURALUDON[];
extern const u8 DEX_ENTRY_DREEPY[];
extern const u8 DEX_ENTRY_DRAKLOAK[];
extern const u8 DEX_ENTRY_DRAGAPULT[];
extern const u8 DEX_ENTRY_KUBFU[];
extern const u8 DEX_ENTRY_URSHIFU_SINGLE[];
extern const u8 DEX_ENTRY_ZARUDE[];
extern const u8 DEX_ENTRY_GLASTRIER[];
extern const u8 DEX_ENTRY_SPECTRIER[];

extern const u8 DEX_ENTRY_RATTATA_A[];
extern const u8 DEX_ENTRY_RATICATE_A[];
extern const u8 DEX_ENTRY_RAICHU_A[];
extern const u8 DEX_ENTRY_SANDSHREW_A[];
extern const u8 DEX_ENTRY_SANDSLASH_A[];
extern const u8 DEX_ENTRY_VULPIX_A[];
extern const u8 DEX_ENTRY_NINETALES_A[];
extern const u8 DEX_ENTRY_DIGLETT_A[];
extern const u8 DEX_ENTRY_DUGTRIO_A[];
extern const u8 DEX_ENTRY_MEOWTH_A[];
extern const u8 DEX_ENTRY_MEOWTH_G[];
extern const u8 DEX_ENTRY_PERSIAN_A[];
extern const u8 DEX_ENTRY_GEODUDE_A[];
extern const u8 DEX_ENTRY_GRAVELER_A[];
extern const u8 DEX_ENTRY_GOLEM_A[];
extern const u8 DEX_ENTRY_PONYTA_G[];
extern const u8 DEX_ENTRY_RAPIDASH_G[];
extern const u8 DEX_ENTRY_SLOWPOKE_G[];
extern const u8 DEX_ENTRY_SLOWBRO_G[];
extern const u8 DEX_ENTRY_FARFETCHD_G[];
extern const u8 DEX_ENTRY_GRIMER_A[];
extern const u8 DEX_ENTRY_MUK_A[];
extern const u8 DEX_ENTRY_EXEGGUTOR_A[];
extern const u8 DEX_ENTRY_MAROWAK_A[];
extern const u8 DEX_ENTRY_WEEZING_G[];
extern const u8 DEX_ENTRY_MR_MIME_G[];
extern const u8 DEX_ENTRY_ARTICUNO_G[];
extern const u8 DEX_ENTRY_ZAPDOS_G[];
extern const u8 DEX_ENTRY_MOLTRES_G[];
extern const u8 DEX_ENTRY_SLOWKING_G[];
extern const u8 DEX_ENTRY_CORSOLA_G[];
extern const u8 DEX_ENTRY_ZIGZAGOON_G[];
extern const u8 DEX_ENTRY_LINOONE_G[];
extern const u8 DEX_ENTRY_DARUMAKA_G[];
extern const u8 DEX_ENTRY_DARMANITAN_G[];
extern const u8 DEX_ENTRY_DARMANITAN_G_ZEN[];
extern const u8 DEX_ENTRY_YAMASK_G[];
extern const u8 DEX_ENTRY_STUNFISK_G[];
extern const u8 DEX_ENTRY_ORICORIO_Y[];
extern const u8 DEX_ENTRY_ORICORIO_P[];
extern const u8 DEX_ENTRY_ORICORIO_S[];
extern const u8 DEX_ENTRY_LYCANROC_N[];
extern const u8 DEX_ENTRY_LYCANROC_DUSK[];
extern const u8 DEX_ENTRY_WISHIWASHI_S[];
extern const u8 DEX_ENTRY_NECROZMA_DUSK_MANE[];
extern const u8 DEX_ENTRY_NECROZMA_DAWN_WINGS[];
extern const u8 DEX_ENTRY_NECROZMA_ULTRA[];
extern const u8 DEX_ENTRY_CRAMORANT_GULPING[];
extern const u8 DEX_ENTRY_CRAMORANT_GORGING[];
extern const u8 DEX_ENTRY_TOXTRICITY_LOW_KEY[];
extern const u8 DEX_ENTRY_SINISTEA_CHIPPED[];
extern const u8 DEX_ENTRY_POLTEAGEIST_CHIPPED[];
extern const u8 DEX_ENTRY_ALCREMIE_BERRY[];
extern const u8 DEX_ENTRY_ALCREMIE_CLOVER[];
extern const u8 DEX_ENTRY_ALCREMIE_FLOWER[];
extern const u8 DEX_ENTRY_ALCREMIE_LOVE[];
extern const u8 DEX_ENTRY_ALCREMIE_RIBBON[];
extern const u8 DEX_ENTRY_ALCREMIE_STAR[];
extern const u8 DEX_ENTRY_EISCUE_NOICE[];
extern const u8 DEX_ENTRY_INDEEDEE_FEMALE[];
extern const u8 DEX_ENTRY_MORPEKO_HANGRY[];
extern const u8 DEX_ENTRY_URSHIFU_RAPID[];
extern const u8 DEX_ENTRY_ZARUDE_DADA[];
