#pragma once

enum MoveTutors
{
	TUTOR00_FIRE_PUNCH,
	TUTOR01_ICE_PUNCH,
	TUTOR02_THUNDER_PUNCH,
	TUTOR03_SNORE,
	TUTOR04_HEAL_BELL,
	TUTOR05_ELECTROWEB,
	TUTOR06_LOW_KICK,
	TUTOR07_UPROAR,
	TUTOR08_BIND,
	TUTOR09_HELPING_HAND,
	TUTOR10_BLOCK,
	TUTOR11_WORRY_SEED,
	TUTOR12_COVET,
	TUTOR13_BUG_BITE,
	TUTOR14_SNATCH,
	TUTOR15_SPITE,
	TUTOR16_AFTER_YOU,
	TUTOR17_SYNTHESIS,
	TUTOR18_SIGNAL_BEAM,
	TUTOR19_GRAVITY,
	TUTOR20_IRON_DEFENSE,
	TUTOR21_TELEKINESIS,
	TUTOR22_MAGNET_RISE,
	TUTOR23_BOUNCE,
	TUTOR24_LAST_RESORT,
	TUTOR25_IRON_HEAD,
	TUTOR26_AQUA_TAIL,
	TUTOR27_PAIN_SPLIT,
	TUTOR28_TAILWIND,
	TUTOR29_ENDEAVOR,
	TUTOR30_ICY_WIND,
	TUTOR31_ZEN_HEADBUTT,
	TUTOR32_SEED_BOMB,
	TUTOR33_LASER_FOCUS,
	TUTOR34_DRAGON_PULSE,
	TUTOR35_DRILL_RUN,
	TUTOR36_MAGIC_COAT,
	TUTOR37_MAGIC_ROOM,
	TUTOR38_WONDER_ROOM,
	TUTOR39_LIQUIDATION,
	TUTOR40_GASTRO_ACID,
	TUTOR41_FOUL_PLAY,
	TUTOR42_SUPER_FANG,
	TUTOR43_OUTRAGE,
	TUTOR44_SKY_ATTACK,
	TUTOR45_THROAT_CHOP,
	TUTOR46_STOMPING_TANTRUM,
	TUTOR47_EARTH_POWER,
	TUTOR48_GUNK_SHOT,
	TUTOR49_DUAL_CHOP,
	TUTOR50_HEAT_WAVE,
	TUTOR51_HYPER_VOICE,
	TUTOR52_SUPERPOWER,
	TUTOR53_GRASS_PLEDGE,
	TUTOR54_FIRE_PLEDGE,
	TUTOR55_WATER_PLEDGE,
	TUTOR56_FRENZY_PLANT,
	TUTOR57_BLAST_BURN,
	TUTOR58_HYDRO_CANNON,
	TUTOR59_NASTY_PLOT,
	TUTOR60_GRASSY_TERRAIN,
	TUTOR61_MISTY_TERRAIN,
	TUTOR62_ELECTRIC_TERRAIN,
	TUTOR63_PSYCHIC_TERRAIN,

//Special Move Tutors - Not in Table
	TUTOR_SPECIAL_DRACO_METEOR,			//128 - Dragon Pokemon
	TUTOR_SPECIAL_SECRET_SWORD,			//129 - Keldeo only
	TUTOR_SPECIAL_RELIC_SONG,			//130 - Meloetta only
	TUTOR_SPECIAL_VOLT_TACKLE,			//131 - Pikachu only
	TUTOR_SPECIAL_DRAGON_ASCENT,		//132 - Rayquaza only
	TUTOR_SPECIAL_THOUSAND_ARROWS,		//133 - Zygarde only
	TUTOR_SPECIAL_THOUSAND_WAVES,		//134 - Zygarde only
	TUTOR_SPECIAL_CORE_ENFORCER,		//135 - Zygarde only
	TUTOR_SPECIAL_STEEL_BEAM,			//136 - Steel Pokemon
};

#define LAST_TOTAL_TUTOR_NUM 136
