#pragma once

enum MoveTutors
{
	TUTOR00_FIRE_PUNCH,
	TUTOR01_ICE_PUNCH,
	TUTOR02_THUNDER_PUNCH,
	TUTOR03_SNORE,
	TUTOR04_HEAL_BELL,
	TUTOR05_ELECTROWEB,
	TUTOR06_LOW_KICK,
	TUTOR07_UPROAR,
	TUTOR08_BIND,
	TUTOR09_HELPING_HAND,
	TUTOR10_BLOCK,
	TUTOR11_WORRY_SEED,
	TUTOR12_COVET,
	TUTOR13_BUG_BITE,
	TUTOR14_SNATCH,
	TUTOR15_SPITE,
	TUTOR16_AFTER_YOU,
	TUTOR17_SYNTHESIS,
	TUTOR18_SIGNAL_BEAM,
	TUTOR19_GRAVITY,
	TUTOR20_IRON_DEFENSE,
	TUTOR21_TELEKINESIS,
	TUTOR22_MAGNET_RISE,
	TUTOR23_BOUNCE,
	TUTOR24_LAST_RESORT,
	TUTOR25_IRON_HEAD,
	TUTOR26_AQUA_TAIL,
	TUTOR27_PAIN_SPLIT,
	TUTOR28_TAILWIND,
	TUTOR29_ENDEAVOR,
	TUTOR30_ICY_WIND,
	TUTOR31_ZEN_HEADBUTT,
	TUTOR32_SEED_BOMB,
	TUTOR33_LASER_FOCUS,
	TUTOR34_DRAGON_PULSE,
	TUTOR35_DRILL_RUN,
	TUTOR36_MAGIC_COAT,
	TUTOR37_MAGIC_ROOM,
	TUTOR38_WONDER_ROOM,
	TUTOR39_LIQUIDATION,
	TUTOR40_GASTRO_ACID,
	TUTOR41_FOUL_PLAY,
	TUTOR42_SUPER_FANG,
	TUTOR43_OUTRAGE,
	TUTOR44_SKY_ATTACK,
	TUTOR45_THROAT_CHOP,
	TUTOR46_STOMPING_TANTRUM,
	TUTOR47_EARTH_POWER,
	TUTOR48_GUNK_SHOT,
	TUTOR49_DUAL_CHOP,
	TUTOR50_HEAT_WAVE,
	TUTOR51_HYPER_VOICE,
	TUTOR52_SUPERPOWER,
	TUTOR53_GRASS_PLEDGE,
	TUTOR54_FIRE_PLEDGE,
	TUTOR55_WATER_PLEDGE,
	TUTOR56_FRENZY_PLANT,
	TUTOR57_BLAST_BURN,
	TUTOR58_HYDRO_CANNON,
	TUTOR59_NASTY_PLOT,
	TUTOR60_GRASSY_TERRAIN,
	TUTOR61_MISTY_TERRAIN,
	TUTOR62_ELECTRIC_TERRAIN,
	TUTOR63_PSYCHIC_TERRAIN,
	TUTOR64_GIGA_DRAIN,
	TUTOR65_CLOSE_COMBAT,
	TUTOR66_AVALANCHE,
	TUTOR67_DRAGON_DANCE,
	TUTOR68_GRASSY_GLIDE,
	TUTOR69_WEATHER_BALL,
	TUTOR70_BRAVE_BIRD,
	TUTOR71_SCORCHING_SANDS,
	TUTOR72_BODY_PRESS,
	TUTOR73_HURRICANE,
	TUTOR74_POLLEN_PUFF,
	TUTOR75_BATON_PASS,
	TUTOR76_PSYCHIC_FANGS,
	TUTOR77_DEFOG,
	TUTOR78_PLAY_ROUGH,
	TUTOR79_FIRE_FANG,
	TUTOR80_THUNDER_FANG,
	TUTOR81_ICE_FANG,
	TUTOR82_POWER_WHIP,
	TUTOR83_COSMIC_POWER,
	TUTOR84_STORED_POWER,
	TUTOR85_DUAL_WINGBEAT,
	TUTOR86_BURNING_JEALOUSY,
	TUTOR87_CROSS_POISON,
	TUTOR88_LEAF_BLADE,
	TUTOR89_POWER_GEM,
	TUTOR90_DARKEST_LARIAT,
	TUTOR91_MOONBLAST,
	TUTOR92_AURA_SPHERE,
	TUTOR93_SKITTER_SMACK,
	TUTOR94_POLTERGEIST,
	TUTOR95_HIGH_HORSEPOWER,

//Special Move Tutors - Not in Table
	TUTOR_SPECIAL_DRACO_METEOR,			//96 - Dragon Pokemon
	TUTOR_SPECIAL_SECRET_SWORD,			//97 - Keldeo only
	TUTOR_SPECIAL_RELIC_SONG,			//98 - Meloetta only
	TUTOR_SPECIAL_VOLT_TACKLE,			//99 - Pikachu only
	TUTOR_SPECIAL_DRAGON_ASCENT,		//100 - Rayquaza only
	TUTOR_SPECIAL_THOUSAND_ARROWS,		//101 - Zygarde only
	TUTOR_SPECIAL_THOUSAND_WAVES,		//102 - Zygarde only
	TUTOR_SPECIAL_CORE_ENFORCER,		//103- Zygarde only
	TUTOR_SPECIAL_STEEL_BEAM,			//104 - Steel Pokemon
	TUTOR_SPECIAL_ASSIST,				//105 - Normal Pokemon
	TUTOR_SPECIAL_SECRETPOWER,			//106 - Normal Pokemon
	TUTOR_SPECIAL_PAYDAY,				//107 - Normal Pokemon
	TUTOR_SPECIAL_FLAMEBURST,			//108 - Fire Pokemon
	TUTOR_SPECIAL_MYSTICALFIRE,			//109 - Fire Pokemon
	TUTOR_SPECIAL_INCINERATE,			//110 - Fire Pokemon
	TUTOR_SPECIAL_AQUARING,				//111 - Water Pokemon
	TUTOR_SPECIAL_BRINE,				//112 - Water Pokemon
	TUTOR_SPECIAL_RAZORSHELL,			//113 - Water Pokemon
	TUTOR_SPECIAL_SPARK,				//114 - Electric Pokemon
	TUTOR_SPECIAL_SHOCKWAVE,			//115 - Electric Pokemon
	TUTOR_SPECIAL_PARABOLICCHARGE,		//116 - Electric Pokemon
	TUTOR_SPECIAL_COTTONSPORE,			//117 - Grass Pokemon
	TUTOR_SPECIAL_FORESTSCURSE,			//118 - Grass Pokemon
	TUTOR_SPECIAL_MEGADRAIN,			//119 - Grass Pokemon
	TUTOR_SPECIAL_ICESHARD,				//120 - Ice Pokemon
	TUTOR_SPECIAL_FREEZEDRY,			//121 - Ice Pokemon
	TUTOR_SPECIAL_AURORABEAM,			//122 - Ice Pokemon
	TUTOR_SPECIAL_KARATECHOP,			//123 - Fighting Pokemon
	TUTOR_SPECIAL_VACUUMWAVE,			//124 - Fighting Pokemon
	TUTOR_SPECIAL_STORMTHROW,			//125 - Fighting Pokemon
	TUTOR_SPECIAL_SLUDGE,				//126 - Poison Pokemon
	TUTOR_SPECIAL_ACIDSPRAY,			//127 - Poison Pokemon
	TUTOR_SPECIAL_COIL,					//128 - Poison Pokemon
	TUTOR_SPECIAL_MUDSHOT,				//129 - Ground Pokemon
	TUTOR_SPECIAL_SPIKES,				//130 - Ground Pokemon
	TUTOR_SPECIAL_MAGNITUDE,			//131 - Ground Pokemon
	TUTOR_SPECIAL_CHATTER,				//132 - Flying Pokemon
	TUTOR_SPECIAL_PLUCK,				//133 - Flying Pokemon
	TUTOR_SPECIAL_SKYDROP,				//134 - Flying Pokemon
	TUTOR_SPECIAL_HEALBLOCK,			//135 - Psychic Pokemon
	TUTOR_SPECIAL_PSYWAVE,				//136 - Psychic Pokemon
	TUTOR_SPECIAL_MAGICPOWDER,			//137 - Psychic Pokemon
	TUTOR_SPECIAL_FURYCUTTER,			//138 - Bug Pokemon
	TUTOR_SPECIAL_FELLSTINGER,			//139 - Bug Pokemon
	TUTOR_SPECIAL_RAGEPOWDER,			//140 - Bug Pokemon
	TUTOR_SPECIAL_ROLLOUT,				//141 - Rock Pokemon
	TUTOR_SPECIAL_WIDEGUARD,			//142 - Rock Pokemon
	TUTOR_SPECIAL_ANCIENTPOWER,			//143 - Rock Pokemon
	TUTOR_SPECIAL_DESTINYBOND,			//144 - Ghost Pokemon
	TUTOR_SPECIAL_SHADOWSNEAK,			//145 - Ghost Pokemon
	TUTOR_SPECIAL_GRUDGE,				//146 - Ghost Pokemon
	TUTOR_SPECIAL_BREAKINGSWIPE,		//147 - Dragon Pokemon
	TUTOR_SPECIAL_SCALESHOT,			//148 - Dragon Pokemon
	TUTOR_SPECIAL_DRAGONRUSH,			//149 - Dragon Pokemon
	TUTOR_SPECIAL_FAKETEARS,			//150 - Dark Pokemon
	TUTOR_SPECIAL_SUCKERPUNCH,			//151 - Dark Pokemon
	TUTOR_SPECIAL_PURSUIT,				//152 - Dark Pokemon
	TUTOR_SPECIAL_AUTOMIZE,				//153 - Steel Pokemon
	TUTOR_SPECIAL_METALBURST,			//154 - Steel Pokemon
	TUTOR_SPECIAL_HEAVYSLAM,			//155 - Steel Pokemon
	TUTOR_SPECIAL_CRAFTYSHIELD,			//156 - Fairy Pokemon
	TUTOR_SPECIAL_DRAININGKISS,			//157 - Fairy Pokemon
	TUTOR_SPECIAL_SPIRITBREAK,			//158 - Fairy Pokemon
};

#define LAST_TOTAL_TUTOR_NUM 158
